### ISSUE TITLE
infoOnClick problem

### ISSUE THREAD

**Issue by marcoas** [plank/MarkerClusterer#1]
Sorry for my English.

If I click repeatedly in a markerCluster with infoOnClick = true, then will be opened several infoWindows. Those infoWindows, then, must be closed one by one.

Its possible have more control for this event ?
## Thanks

Marco A.S.

**Comment by meeech** [comment]
Hi Marcaos, yes, it should be possible.
You would basically have to store the current open one, and close it before reopening.
